server:
  port: 8888
spring:
  profiles:
    active: native # for using config resource from classpath instead of git
    # searches in classpath:/ , classpath:/config, and file:./config
  application:
    name: config
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
#        git:
#          uri: http:// path to git url
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
security:
  user:
    name: config
    password: config